### ISSUE TITLE
Error wenn ein Anime mehr als 1 Staffel enthält.

### ISSUE THREAD

**Issue by palpex** [Someone266/aniworld-downloader#7]
😱 
![image](https://github.com/user-attachments/assets/0c2928ab-4811-424c-b04a-ca2a1dbb6ce8)

es hat einen download lang funktioniert und dann auch einmal suchen, aber jetzt geht wieder nix
edit: es lebt wieder
nun bekomme ich `KeyError: '2'` 
Hier irgendein anime als beispiel:
![image](https://github.com/user-attachments/assets/babf9493-ca72-4a84-aebd-354f5270c6bf)
Bei anderen geht es aber wieder?!
edit: scheint ein Problem mit allen Animes welche mehr als eine Staffel haben zu sein

_Originally posted by @palpex in https://github.com/Someone266/aniworld-downloader/issues/3#issuecomment-2246348842_

**Comment by EvilBlood** [comment]
Gleicher Fehler hier:

←[96m    AA          W     W         ll     d     DDD                    ←[0m
←[96m   A  A      ii W     W          l     d     D  D                   ←[0m
←[96m   AAAA nnn     W  W  W ooo rrr  l   ddd     D  D ooo w   w nnn     ←[0m
←[96m   A  A n  n ii  W W W  o o r    l  d  d     D  D o o w w w n  n    ←[0m
←[96m   A  A n  n ii   W W   ooo r   lll  ddd     DDD  ooo  w w  n  n    ←[0m
←[96m                                                                    ←[0m
A powerful scraper and downloader for AniWorld

Version: 1.1.8 (Windows)                                 Made by JMcrafter26
←[90mDISCLAIMER: This is a scraper for educational purposes only. I am not responsible for any misuse of this code.←[0m
←[90mPlease respect the laws of your country and the country of the website you are scraping.←[0m


Press one of the following keys:
1. Download Assistant
2. Continue Download
3. Serve content
4. Clean up
5. Open anime folder
6. Get anime info
0. Settings
h. Help/Info
q. Quit
1
←[H←[J


←[96m    AA          W     W         ll     d     DDD                    ←[0m
←[96m   A  A      ii W     W          l     d     D  D                   ←[0m
←[96m   AAAA nnn     W  W  W ooo rrr  l   ddd     D  D ooo w   w nnn     ←[0m
←[96m   A  A n  n ii  W W W  o o r    l  d  d     D  D o o w w w n  n    ←[0m
←[96m   A  A n  n ii   W W   ooo r   lll  ddd     DDD  ooo  w w  n  n    ←[0m
←[96m                                                                    ←[0m
A powerful scraper and downloader for AniWorld

Version: 1.1.8 (Windows)                                 Made by JMcrafter26
←[90mDISCLAIMER: This is a scraper for educational purposes only. I am not responsible for any misuse of this code.←[0m
←[90mPlease respect the laws of your country and the country of the website you are scraping.←[0m


←[92mThis is the auto mode. It will ask you what to download.←[0m


Enter the name of the anime you want to search for or paste the url of the anime
https://aniworld.to/anime/stream/way-of-the-househusband
Getting info for: Way of the Househusband
FINISHED (2021 - 2023) - 15 episodes - 2 seasons
Setting up anime folder...
Anime folder setup complete
Getting streams for season 1 with 10 episodes...
Path: Way of the Househusband (2021-2023)
Found stream.json
Checking if season already exists...
Season stream urls already exist
Getting streams for season 2 with 5 episodes...
Path: Way of the Househusband (2021-2023)
Found stream.json
Checking if season already exists...
Traceback (most recent call last):
  File "main_win.py", line 592, in <module>
  File "main_win.py", line 575, in handleCommands
  File "main_win.py", line 375, in startUi
  File "main_win.py", line 532, in runAuto
  File "main_win.py", line 203, in getSeasonDownloads
KeyError: '2'
[47236] Failed to execute script 'main_win' due to unhandled exception!
PS D:\Downloads\AniworldDown2>

**Comment by JMcrafter26** [comment]
Sorry für die Wartezeit, ich habe das Problem behoben und werde es demnächst veröffentlichen.
Sollte es weitere Probleme geben, öffnet einfach ein neues Issue

**Comment by JMcrafter26** [comment]
Hi,
Ich habe vor ein paar Wochen ein Update herausgebracht. Mich würde es sehr interessieren ob der Fehler behoben wurde.
Danke :)
