### ISSUE TITLE
Update 1.1.18 js2py Bug

### ISSUE THREAD

**Issue by palpex** [Someone266/aniworld-downloader#8]
Ich habe js2py installiert und bekomme diesen error seit Update 18:
`ython3 main.py
Traceback (most recent call last):
  File "/mnt/hdd/palpex/AniDown/main.py", line 145, in <module>
    import requests as R,bs4 as w,js2py,re as g
  File "/usr/local/lib/python3.12/dist-packages/js2py/__init__.py", line 72, in <module>
    from .base import PyJsException
  File "/usr/local/lib/python3.12/dist-packages/js2py/base.py", line 2965, in <module>
    @Js
     ^^
  File "/usr/local/lib/python3.12/dist-packages/js2py/base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/js2py/base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/js2py/utils/injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/js2py/utils/injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3`

_Originally posted by @palpex in https://github.com/Someone266/aniworld-downloader/issues/3#issuecomment-2248917909_

**Comment by JMcrafter26** [comment]
Verwendest du voe als Download?

**Comment by palpex** [comment]
Jo und sorry wegen der neuen issues hast auf das alte nicht mehr geantwortet, hab's mal gecloset

**Comment by JMcrafter26** [comment]
Kein Problem. Ich habe zurzeit viel um die Ohren und kann deshalb nicht so viel Zeit in das Projekt investieren. Sollte ich Zeit haben, werde ich mir die issues ansehen und die bugs fixen.

**Comment by palpex** [comment]
Okay, gut zu wissen. Dann viel Erfolg und ich liebe das Projekt! Ich bastel gerade an einer Watch Seite die sichert wie weit man eine Folge gesehen hat, und diese dort weiter abspielt wo man sie beendet hat. Und mit Farben anzeigt ob sie zu Ende gesehen wurde oder nicht. Ich werde aber auch nicht viel schaffen, weil ich ab Freitag im Urlaub bin. Ich schau aber trotzdem zwischendurch mal hier vorbei

**Comment by palpex** [comment]
Hab's gelöst. Mit python 3.10 und der passenden pip Version (sowie js2py für Python 3.10) startet die Datei ohne Probleme.
